function(yaml_fortran_cxx_library target include_dirs public_link_libraries)
    set_target_properties(${target} PROPERTIES INSTALL_RPATH "\$ORIGIN/../${CMAKE_INSTALL_LIBDIR}")
    target_link_libraries(${target} PUBLIC ${public_link_libraries})
    target_include_directories(${target} PUBLIC ${include_dirs})
endfunction()
